{
 "title": "RedisGears WriteBehind Demo",
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Databases",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Per Second" }
   ],
   "targets": [
    {
     "alias": "MySQL INSERTed/UPDATEd rows",
     "measurement": "mysql_mysql",
     "query": "SELECT derivative(\"innodb_rows_inserted\", 1s) + derivative(\"innodb_rows_updated\", 1s) FROM \"mysql_mysql\" WHERE (\"server\" = 'db:3306') AND $timeFilter",
     "select": [
      [
       { "params": [ "innodb_rows_inserted" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "server", "operator": "=", "value": "db:3306" }
     ]
    },
    {
     "alias": "Standalone Redis HMSET operations",
     "groupBy": [
      { "params": [ "port" ], "type": "tag" }
     ],
     "measurement": "redis_cmdstat",
     "query": "SELECT SUM(\"derivative\") FROM (SELECT derivative(\"calls\", 1s) FROM \"redis_cmdstat\" WHERE (\"command\" = 'hmset' AND \"port\" = '6379') AND $timeFilter GROUP BY \"port\") GROUP BY time(1s) fill(0)",
     "select": [
      [
       { "params": [ "calls" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=", "value": "hmset" },
      { "condition": "AND", "key": "port", "operator": "=", "value": "6379" }
     ]
    },
    {
     "alias": "Redis Cluster HMSET operations",
     "groupBy": [
      { "params": [ "port" ], "type": "tag" }
     ],
     "measurement": "redis_cmdstat",
     "query": "SELECT SUM(\"derivative\") FROM (SELECT derivative(\"calls\", 1s) FROM \"redis_cmdstat\" WHERE (\"command\" = 'hmset' AND \"port\" != '6379') AND $timeFilter GROUP BY \"port\") GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "calls" ], "type": "field" },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "command", "operator": "=", "value": "hmset" },
      { "condition": "AND", "key": "port", "operator": "=", "value": "6379" }
     ]
    }
   ]
  },
  {
   "title": "Application Requests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short", "label": "Per Second" }
   ],
   "targets": [
    {
     "alias": "Requests",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_reqs",
     "query": "SELECT count(\"value\") FROM \"http_reqs\" WHERE $timeFilter GROUP BY time(1s) fill(0)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Application Latency",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "short", "label": "Milliseconds" }
   ],
   "targets": [
    {
     "alias": "95 percentile",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [
         95
        ],
        "type": "percentile"
       }
      ]
     ]
    },
    {
     "alias": "Mean",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "alias": "Median",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "0" ], "type": "fill" }
     ],
     "measurement": "http_req_duration",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "median"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Redis CPU",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "percentunit", "label": "Load" }
   ],
   "targets": [
    {
     "alias": "sys",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "redis",
     "query": "SELECT SUM(\"d\") FROM (SELECT derivative(max(\"used_cpu_sys\"), 1s) + derivative(max(\"used_cpu_sys_children\"), 1s) AS \"d\" FROM \"redis\" WHERE $timeFilter GROUP BY \"port\") GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "used_cpu_sys" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ],
      [
       { "params": [ "used_cpu_sys_children" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "port", "operator": "=", "value": "6379" }
     ]
    },
    {
     "alias": "user",
     "groupBy": [
      { "params": [ "1s" ], "type": "time" },
      { "params": [ "previous" ], "type": "fill" }
     ],
     "measurement": "redis",
     "query": "SELECT SUM(\"d\") FROM (SELECT derivative(max(\"used_cpu_user\"), 1s) + derivative(max(\"used_cpu_user_children\"), 1s) AS \"d\" FROM \"redis\" WHERE $timeFilter GROUP BY \"port\") GROUP BY time(1s) fill(linear)",
     "select": [
      [
       { "params": [ "used_cpu_sys" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ],
      [
       { "params": [ "used_cpu_sys_children" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "1s" ], "type": "derivative" }
      ]
     ],
     "tags": [
      { "key": "port", "operator": "=", "value": "6379" }
     ]
    }
   ]
  }
 ]
}